export const CREATE_HOLIDAY = "CREATE_HOLIDAY";
export const CREATE_HOLIDAY_SUCCESS = "CREATE_HOLIDAY_SUCCESS";
export const CREATE_HOLIDAY_ERROR = "CREATE_HOLIDAY_ERROR";

export const GET_HOLIDAY = "GET_HOLIDAY";
export const GET_HOLIDAY_SUCCESS = "GET_HOLIDAY_SUCCESS";
export const GET_HOLIDAY_ERROR = "GET_HOLIDAY_ERROR";

export const DELETE_HOLIDAY = "DELETE_HOLIDAY";
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_ERROR = "DELETE_HOLIDAY_ERROR";
