export const CREATE_ABSENT = "CREATE_ABSENT";
export const CREATE_ABSENT_SUCCESS = "CREATE_ABSENT_SUCCESS";
export const CREATE_ABSENT_ERROR = "CREATE_ABSENT_ERROR";

export const GET_ABSENT = "GET_ABSENT";
export const GET_ABSENT_SUCCESS = "GET_ABSENT_SUCCESS";
export const GET_ABSENT_ERROR = "GET_ABSENT_ERROR";
