export const CREATE_PRESENT = "CREATE_PRESENT";
export const CREATE_PRESENT_SUCCESS = "CREATE_PRESENT_SUCCESS";
export const CREATE_PRESENT_ERROR = "CREATE_PRESENT_ERROR";

export const GET_PRESENT = "GET_PRESENT";
export const GET_PRESENT_SUCCESS = "GET_PRESENT_SUCCESS";
export const GET_PRESENT_ERROR = "GET_PRESENT_ERROR";

export const DELETE_PRESENT = "DELETE_HOLIDAY";
export const DELETE_PRESENT_SUCCESS = "DELETE_PRESENT_SUCCESS";
export const DELETE_PRESENT_ERROR = "DELETE_PRESENT_ERROR";
