export const CREATE_BLOG = "CREATE_BLOG";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";

export const GET_BLOG = "GET_BLOG";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";

// export const DELETE_BLOG = "DELETE_BLOG";
// export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
// export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";